import { debt, SHADCN_FILES, svelteConfig } from "@nocturne/eslint-config";

export default [
  // components.json points the theme at @nocturne/ui's, which portal renders cms with.
  ...svelteConfig({ shadcnSettings: { ui: "@nocturne/ui/ui" } }),
  {
    // Build-time tooling over the repo's own files: every path is built from the package
    // root or a checked-in manifest, never from a request.
    files: ["src/blog/vite-plugin.ts", "src/email/build.ts"],
    rules: { "security/detect-non-literal-fs-filename": "off" }
  },
  {
    // The editor's plain-CSS hooks, styled by src/lib/components/edra/editor.css rather than
    // generated by Tailwind; `lead` and `not-prose` repeat the shared config's allowance.
    files: SHADCN_FILES,
    rules: {
      "shadcn/no-unknown-classes": [
        "error",
        { allow: ["lead", "not-prose", "edra-editor", "code-wrapper", "code-wrapper-tile", "drag-handle"] }
      ]
    }
  },
  ...debt({
    "shadcn/require-static-classes": 6,
    "shadcn/no-restyle": 93,
    "no-restricted-syntax": 20
  })
];
