namespace Nocturne.Connectors.MyLife.Mappers.Constants;

public enum MyLifeEventType
{
    Glucose = 1,
    ManualGlucose = 2,
    TotalDailyDose = 3,
    TempBasal = 4,
    BolusNormal = 5,
    BolusSquare = 6,
    BolusDual = 7,
    CarbCorrection = 8,
    PodActivated = 10,
    PodDeactivated = 11,
    PumpSuspend = 12,
    PumpResume = 13,
    Alert = 14,
    DateChanged = 15,
    TimeChanged = 16,
    BasalRate = 17,
    Indication = 18,
    SiteChange = 19,
    Priming = 20,
    Rewind = 21,
    Basal = 22,
    TubePriming = 23,
    NeedlePriming = 24,
    BolusMaxChanged = 25,
    BasalMaxChanged = 26,
    ManualGlucoseAlt = 27,
    CgmGap = 28,
    CgmSession = 30,
}
