namespace Nocturne.Core.Constants;

/// <summary>
/// Defines data source identifiers for tracking the provenance of entries, treatments, and other data.
/// Used to identify where data originated from, enabling source-specific filtering, cleanup, and auditing.
/// </summary>
/// <remarks>
/// Replaces the previous IsDemo boolean approach with a more flexible, extensible string-based system.
/// Every piece of data in Nocturne can be traced back to its source using these identifiers.
/// </remarks>
public static class DataSources
{
    // ============================================================================
    // Demo / Development Sources
    // ============================================================================

    /// <summary>
    /// Data generated by the demo service for demonstration/testing purposes.
    /// This data is synthetic and can be safely deleted without affecting real health data.
    /// </summary>
    public const string DemoService = "demo-service";

    /// <summary>
    /// Data created during automated testing (unit tests, integration tests).
    /// Should never appear in production databases.
    /// </summary>
    public const string Testing = "testing";

    // ============================================================================
    // CGM Connector Sources
    // ============================================================================

    /// <summary>
    /// Data fetched from Dexcom Share/Clarity API via the Dexcom connector.
    /// </summary>
    public const string DexcomConnector = "dexcom-connector";

    /// <summary>
    /// Data fetched from FreeStyle Libre (LibreLinkUp) via the Libre connector.
    /// </summary>
    public const string LibreConnector = "libre-connector";

    /// <summary>
    /// Data fetched from Medtronic CareLink via the MiniMed connector.
    /// </summary>
    public const string MiniMedConnector = "minimed-connector";

    /// <summary>
    /// Data fetched from Glooko API via the Glooko connector.
    /// </summary>
    public const string GlookoConnector = "glooko-connector";

    /// <summary>
    /// Data bridged from an upstream Nightscout instance via the Nightscout connector.
    /// </summary>
    public const string NightscoutConnector = "nightscout-connector";

    /// <summary>
    /// Data fetched from Tidepool API.
    /// </summary>
    public const string TidepoolConnector = "tidepool-connector";

    /// <summary>
    /// Data fetched from Tandem Source via the TConnectSync connector.
    /// </summary>
    public const string TConnectSyncConnector = "tconnectsync-connector";

    /// <summary>
    /// Data from xDrip+ Android app.
    /// </summary>
    public const string XDrip = "xdrip";

    /// <summary>
    /// Data from Spike iOS app.
    /// </summary>
    public const string Spike = "spike";

    /// <summary>
    /// Data fetched from MyFitnessPal via the MyFitnessPal connector.
    /// </summary>
    public const string MyFitnessPalConnector = "myfitnesspal-connector";

    public const string MyLifeConnector = "mylife-connector";

    // ============================================================================
    // Manual Entry Sources
    // ============================================================================


    /// <summary>
    /// Data entered manually by a user through the Nocturne web interface.
    /// </summary>
    public const string ManualEntry = "manual";

    /// <summary>
    /// Data entered via the Nightscout Careportal interface.
    /// </summary>
    public const string Careportal = "careportal";

    /// <summary>
    /// Data entered via the Nightscout API by a client application.
    /// </summary>
    public const string ApiClient = "api-client";

    // ============================================================================
    // Import / Migration Sources
    // ============================================================================

    /// <summary>
    /// Data imported from a legacy MongoDB Nightscout database during migration.
    /// </summary>
    public const string MongoDbImport = "mongodb-import";

    /// <summary>
    /// Data imported from a CSV file.
    /// </summary>
    public const string CsvImport = "csv-import";

    /// <summary>
    /// Data imported from Tidepool export.
    /// </summary>
    public const string TidepoolImport = "tidepool-import";

    /// <summary>
    /// Data imported from an unknown or unspecified source.
    /// Used as a fallback when the source cannot be determined.
    /// </summary>
    public const string Unknown = "unknown";

    // ============================================================================
    // System Sources
    // ============================================================================

    /// <summary>
    /// Data generated by system processes (e.g., calculated fields, aggregations).
    /// </summary>
    public const string System = "system";

    /// <summary>
    /// Data received via WebSocket real-time push.
    /// </summary>
    public const string WebSocket = "websocket";

    // ============================================================================
    // AID/Loop System Sources
    // ============================================================================

    /// <summary>
    /// Data from Loop iOS app.
    /// </summary>
    public const string Loop = "loop";

    /// <summary>
    /// Data from OpenAPS system.
    /// </summary>
    public const string OpenAps = "openaps";

    /// <summary>
    /// Data from AndroidAPS (AAPS) app.
    /// </summary>
    public const string AndroidAps = "aaps";

    /// <summary>
    /// Data from iAPS app.
    /// </summary>
    public const string IAps = "iaps";

    /// <summary>
    /// Data from Trio app.
    /// </summary>
    public const string Trio = "trio";

    // ============================================================================
    // Helper Methods
    // ============================================================================

    /// <summary>
    /// Returns true if the data source represents demo/test data that can be safely deleted.
    /// </summary>
    public static bool IsEphemeral(string? dataSource)
    {
        return dataSource is DemoService or Testing;
    }

    /// <summary>
    /// Returns true if the data source represents data from a CGM connector.
    /// </summary>
    public static bool IsConnector(string? dataSource)
    {
        return dataSource
            is DexcomConnector
                or LibreConnector
                or MiniMedConnector
                or GlookoConnector
                or NightscoutConnector
                or TidepoolConnector
                or TConnectSyncConnector;
    }

    /// <summary>
    /// Returns true if the data source represents manually entered data.
    /// </summary>
    public static bool IsManualEntry(string? dataSource)
    {
        return dataSource is ManualEntry or Careportal or ApiClient;
    }

    /// <summary>
    /// Returns true if the data source represents imported/migrated data.
    /// </summary>
    public static bool IsImported(string? dataSource)
    {
        return dataSource is MongoDbImport or CsvImport or TidepoolImport;
    }

    /// <summary>
    /// Returns true if the data source represents data from an AID/closed-loop system.
    /// </summary>
    public static bool IsAidSystem(string? dataSource)
    {
        return dataSource is Loop or OpenAps or AndroidAps or IAps or Trio;
    }

    /// <summary>
    /// Gets all known data source values.
    /// </summary>
    public static IReadOnlyList<string> All { get; } =
        new[]
        {
            DemoService,
            Testing,
            DexcomConnector,
            LibreConnector,
            MiniMedConnector,
            GlookoConnector,
            NightscoutConnector,
            TidepoolConnector,
            TConnectSyncConnector,
            XDrip,
            Spike,
            ManualEntry,
            Careportal,
            ApiClient,
            MongoDbImport,
            CsvImport,
            TidepoolImport,
            Unknown,
            System,
            WebSocket,
            Loop,
            OpenAps,
            AndroidAps,
            IAps,
            Trio,
        };
}
