import prettier from "eslint-config-prettier";
import pluginsecurity from "eslint-plugin-security";
import { plugin as shadcn } from "@shadcn/lint";

import js from '@eslint/js';
import svelte from 'eslint-plugin-svelte';
import globals from 'globals';
import ts from 'typescript-eslint';

import noImperativeRemoteQuery from "./tools/eslint/no-imperative-remote-query.js";

// Width stays layout the caller owns; height comes only from a control's size.
const HEIGHT_CLASSES = ["h-*", "size-*", "min-h-*", "max-h-*"];
const CONTROL_HEIGHT_HINT =
  "\"{{className}}\" is not allowed on <{{component}}>: its height comes from size. Use size=\"xs\" (h-7), \"sm\" (h-8) or the default (h-9); each matches the same size on Button, Input, SelectTrigger and Toggle.";

export default ts.config(
  js.configs.recommended,
  ...ts.configs.recommended,
  pluginsecurity.configs.recommended,
  ...svelte.configs["flat/recommended"],
  prettier,
  ...svelte.configs['flat/prettier'],
  {
    languageOptions: {
	  globals: {
	    ...globals.browser,
	    ...globals.node
	  }
	}
  },
  {
    files: ["**/*.svelte", "**/*.svelte.ts"],

    languageOptions: {
	  parserOptions: {
	    parser: ts.parser
	  }
	},
    plugins: { shadcn }
  },
  {
    files: ["**/*.ts"],
    plugins: { shadcn }
  },
  {
    // Generated by the API build; gitignored, so linting it makes counts depend on whether it was built.
    ignores: ["build/", ".svelte-kit/", "dist/", "src/lib/api/generated/**", "src/lib/api/api-client.generated.ts"]
  },
  {
    files: ["**/*.svelte", "**/*.ts"],
    rules: {
      "shadcn/no-restyle": ["warn", {
        allow: ["layout"],
        // A later matching contract replaces an earlier one, so each restates layout.
        contracts: [
          {
            pattern: "^Card(Header|Content|Footer)$|^(Dialog|Sheet|AlertDialog)(Header|Footer)$|^(Popover|Collapsible)Content$",
            allow: ["layout", "spacing"]
          },
          { pattern: "^Table(Cell|Head)$", allow: ["layout", "spacing", "tabular-nums", "font-mono"] },
          { pattern: "^(Card|Dialog|Sheet|AlertDialog)Title$", allow: ["layout", "typography", "gap"] },
          {
            pattern: "^(Input|SelectTrigger)$",
            allow: ["layout", "tabular-nums", "font-mono"],
            deny: HEIGHT_CLASSES,
            message: {
              layout: CONTROL_HEIGHT_HINT,
              spacing: 'Use size="xs" or "sm" on <{{component}}>; each matches the same size on Input, SelectTrigger and ToggleGroup.',
              typography: 'Use size="xs" or "sm" on <{{component}}>; Input also has variant="code" for device codes.',
              color: "Mark an invalid field with aria-invalid, which <{{component}}> already styles."
            }
          },
          { pattern: "^Textarea$", allow: ["layout", "font-mono"] },
          {
            pattern: "^Label$",
            allow: ["layout"],
            message: {
              typography: 'Use <Label size="sm"> or size="lg", or variant="option" for a checkbox, radio or switch choice.',
              color: 'Use <Label variant="muted"> for a secondary caption.'
            }
          },
          {
            pattern: "^ToggleGroup(Item)?$",
            allow: ["layout"],
            deny: HEIGHT_CLASSES,
            message: 'Set it on <ToggleGroup>: size="xs" (h-7) or "sm" (h-8) for a compact row, variant="segmented" for a view switcher, spacing={1} for separate chips.'
          },
          {
            pattern: "^Toggle$",
            allow: ["layout"],
            deny: HEIGHT_CLASSES,
            message: { layout: CONTROL_HEIGHT_HINT }
          },
          // A placeholder takes the radius of the content it stands in for.
          { pattern: "^Skeleton$", allow: ["layout", "rounded"] },
          {
            pattern: "^Button$",
            allow: ["layout"],
            deny: HEIGHT_CLASSES,
            message: {
              layout: "\"{{className}}\" is not allowed on <Button>: its height comes from size. Use xs (h-7), sm (h-8), default (h-9), lg (h-10), xl (h-14, full-screen alarm actions), icon-xs (size-7), icon-sm (size-8), icon (size-9), or inline (h-auto, no padding) for a link in running text. Width stays yours.",
              typography: "\"{{className}}\" is not allowed on <Button>: it owns its type. size=\"xs\" gives text-xs and size=\"xl\" text-lg; every other size is text-sm font-medium."
            }
          },
          {
            pattern: "^(Badge|Alert|Card)(\\.Root)?$",
            allow: ["layout"]
          }
        ]
      }],
      "shadcn/no-raw-colors": "warn",
      "shadcn/no-arbitrary-values": ["warn", { allow: ["layout"], deny: ["text-[10px]", "text-[11px]"] }],
      "shadcn/no-inline-styles": "warn",
      // `lead` is a hook the typography plugin styles inside `prose`.
      "shadcn/no-unknown-classes": ["warn", { allow: ["lead"] }],
      "shadcn/require-static-classes": "warn"
    }
  },
  {
    // Clock faces render styles their owner authored in the clock builder: colours,
    // sizes, positions and free-form custom CSS.
    files: [
      "src/lib/components/clock/**",
      "src/lib/components/clock-builder/**",
      "src/routes/(authenticated)/clock/**"
    ],
    rules: {
      "shadcn/no-inline-styles": "off"
    }
  },
  {
    // Theme cards preview the palettes of themes that are not active, which the
    // active theme's tokens cannot express.
    files: ["src/routes/(authenticated)/settings/appearance/+page.svelte"],
    rules: {
      "shadcn/no-inline-styles": ["warn", { allow: ["background"] }]
    }
  },
  {
    files: ["src/lib/components/ui/**"],
    rules: {
      "shadcn/no-restyle": "off",
      "shadcn/no-arbitrary-values": "off",
      "shadcn/require-static-classes": "off"
    }
  },
  {
    rules: {
      "@typescript-eslint/consistent-type-assertions": [
        "error",
        {
          assertionStyle: "never"
        }
      ],
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_"
        }
      ]
    }
  },
  {
    // Guard against the year-overview/alerts-polling regression class: a remote
    // query() awaited or `.then()`-chained imperatively (outside a reactive
    // context) throws "not created in a reactive context ... Use .run()".
    files: ["**/*.svelte", "**/*.svelte.ts"],
    plugins: {
      nocturne: {
        rules: { "no-imperative-remote-query": noImperativeRemoteQuery }
      }
    },
    rules: {
      "nocturne/no-imperative-remote-query": "warn"
    }
  },
  {
    // @shadcn/lint only sees classes on known components, so a raw control
    // escapes the design system without a finding. Hidden inputs carry form
    // state and render nothing.
    files: ["**/*.svelte"],
    ignores: ["src/lib/components/ui/**", "**/*.test.svelte"],
    rules: {
      "no-restricted-syntax": ["warn",
        {
          selector: 'SvelteElement[kind="html"][name.name="button"]',
          message: "Use <Button> with a variant and size, or <Toggle> for a pressed state, instead of a raw <button>."
        },
        {
          selector: 'SvelteElement[kind="html"][name.name="input"]:not(:has(SvelteAttribute[key.name="type"] > SvelteLiteral[value="hidden"]))',
          message: "Use <Input>, <Checkbox>, <Switch>, <RadioGroup> or <Slider> instead of a raw <input>. type=\"hidden\" is allowed."
        },
        {
          selector: 'SvelteElement[kind="html"][name.name="select"]',
          message: "Use <Select> instead of a raw <select>."
        },
        {
          selector: 'SvelteElement[kind="html"][name.name="textarea"]',
          message: "Use <Textarea> instead of a raw <textarea>."
        },
        {
          selector: "Literal[value=/hsl\\(var\\(--/]",
          message: "Theme variables are oklch; use var(--x) or color-mix(in oklch, var(--x) N%, transparent), not hsl(var(--x))."
        },
        {
          selector: "TemplateElement[value.raw=/hsl\\(var\\(--/]",
          message: "Theme variables are oklch; use var(--x) or color-mix(in oklch, var(--x) N%, transparent), not hsl(var(--x))."
        }
      ]
    }
  }
);
