#pragma warning disable ASPIREPIPELINES001
#pragma warning disable ASPIREPIPELINES004

using Aspire.Hosting;
using Aspire.Hosting.Pipelines;
using Aspire.Hosting.Publishing;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using YamlDotNet.RepresentationModel;

namespace Nocturne.Aspire.Host.Publishing;

public static class ByoProxyComposePublisherExtensions
{
    /// <summary>
    /// Registers a publish pipeline step that emits docker-compose.byo-proxy.yaml — a
    /// compose override that disables the bundled Caddy service and re-exposes the gateway
    /// on a host port so operators can front Nocturne with their own reverse proxy.
    /// The override is derived from the generated docker-compose.yaml (the gateway's
    /// internal port is read from it) so it cannot drift. Emitted only when a caddy
    /// service is present; otherwise there is nothing to override.
    /// </summary>
    public static IDistributedApplicationBuilder AddByoProxyComposePublisher(
        this IDistributedApplicationBuilder builder)
    {
        builder.Pipeline.AddStep(
            name: "byo-proxy-compose",
            action: async ctx =>
            {
                var outputService = ctx.Services.GetRequiredService<IPipelineOutputService>();
                var outputPath = outputService.GetOutputDirectory();

                var composePath = Path.Combine(outputPath, "docker-compose.yaml");
                var rawCompose = await File.ReadAllTextAsync(composePath, ctx.CancellationToken);

                var overrideYaml = BuildByoProxyOverride(rawCompose);
                if (overrideYaml is null)
                {
                    ctx.Logger.LogInformation(
                        "[byo-proxy-publisher] No caddy service in compose; skipping byo-proxy override");
                    return;
                }

                await File.WriteAllTextAsync(
                    Path.Combine(outputPath, "docker-compose.byo-proxy.yaml"),
                    overrideYaml,
                    ctx.CancellationToken);

                ctx.Logger.LogInformation("[byo-proxy-publisher] Wrote docker-compose.byo-proxy.yaml");
            },
            dependsOn: "publish-compose",
            requiredBy: WellKnownPipelineSteps.Publish);

        return builder;
    }

    /// <summary>
    /// Builds the bring-your-own-proxy override from the generated compose, or null when
    /// no caddy service is present. The gateway's host port is taken from its first
    /// internal (expose) port so the override stays in sync with the generated compose.
    /// </summary>
    private static string? BuildByoProxyOverride(string composeYaml)
    {
        var yaml = new YamlStream();
        using (var reader = new StringReader(composeYaml))
            yaml.Load(reader);

        var root = (YamlMappingNode)yaml.Documents[0].RootNode;
        var services = (YamlMappingNode)root["services"];

        // The override only makes sense when Caddy is the bundled edge.
        if (!services.Children.TryGetValue("caddy", out _))
            return null;

        // Derive the gateway's internal container port from its expose list so the
        // host mapping can't drift from the generated compose.
        var gatewayPort = "5000";
        if (services.Children.TryGetValue("gateway", out var gw)
            && gw is YamlMappingNode gwMap
            && gwMap.Children.TryGetValue("expose", out var exposeNode)
            && exposeNode is YamlSequenceNode exposeSeq
            && exposeSeq.Children.Count > 0
            && exposeSeq.Children[0] is YamlScalarNode { Value: { Length: > 0 } } first)
        {
            gatewayPort = first.Value!;
        }

        var lines = new[]
        {
            "# Bring-your-own reverse proxy override.",
            "#",
            "# GENERATED by scripts/publish-release.cs from the Aspire AppHost — do not edit",
            "# by hand. Use it to terminate TLS with your own reverse proxy (nginx, Traefik,",
            "# Caddy, your existing homelab edge, ...) instead of the bundled Caddy: it parks",
            "# Caddy under an inactive profile so it never starts, and exposes the gateway on",
            "# host port 8080 (plain HTTP) for your proxy to forward to.",
            "#",
            "# Usage:",
            "#   docker compose -f docker-compose.yaml -f docker-compose.byo-proxy.yaml up -d",
            "#",
            "# Then point your proxy at http://<host>:8080 and forward the original Host and",
            "# X-Forwarded-* headers. For multi-tenant deployments, terminate the apex AND",
            "# *.your-domain there (e.g. a wildcard certificate obtained via DNS-01).",
            "services:",
            "  caddy:",
            "    profiles: [\"byo-proxy-disabled\"]",
            "  gateway:",
            "    ports:",
            $"      - \"8080:{gatewayPort}\"",
            "",
        };

        return string.Join("\n", lines);
    }
}
