import {
  Artwork,
  DropGroup,
  DropSurface,
  PaintedUnderline,
  SelectionEdge,
  AvatarWash,
  ConfirmationBackground,
  HeaderMotif,
  ARTWORK_IDS,
  PALETTE_IDS,
  DEFAULT_INTENSITY,
  DEFAULT_DURATION_MS,
  DEFAULT_MAX_LIVE_INSTANCES,
  seedFromName,
  detailForEdge,
  createArtworkPlayer,
  getEngineHost,
  configureEngineHost,
  getScheduler,
} from '@nocturne/watercolour';

export {
  Artwork,
  DropGroup,
  DropSurface,
  PaintedUnderline,
  SelectionEdge,
  AvatarWash,
  ConfirmationBackground,
  HeaderMotif,
  ARTWORK_IDS,
  PALETTE_IDS,
  DEFAULT_INTENSITY,
  DEFAULT_DURATION_MS,
  DEFAULT_MAX_LIVE_INSTANCES,
  seedFromName,
  detailForEdge,
  createArtworkPlayer,
  getEngineHost,
  configureEngineHost,
  getScheduler,
};

export type {
  ArtworkId,
  PaletteId,
  ArtworkOptions,
  ArtworkMode,
  ArtworkMotion,
  ArtworkQuality,
  ArtworkAutoplay,
  Surface,
  DetailLevel,
  ArtworkPlayer,
  PlayerOptions,
  PlayerState,
  PlayerEvent,
  FallbackDetail,
  EngineStats,
  EngineHostOptions,
  EngineLease,
  FrameStats,
  DropFont,
  DropFonts,
  DropDeposit,
} from '@nocturne/watercolour';