// AUTO-GENERATED - DO NOT EDIT
// Generated by @nocturne/remote-function-codegen
// Source: openapi.json
//
// Note: Property names are derived from the shared tag-to-property mapping.
// Some may need manual adjustment to match existing api-client.ts conventions.

import {
  ActivityClient,
  BackfillClient,
  AlexaClient,
  AnalyticsClient,
  AuthenticationClient,
  AuthorizationClient,
  BatteryClient,
  ChartDataClient,
  ClockFacesClient,
  CompatibilityClient,
  CompressionLowClient,
  ConfigurationClient,
  ConnectorFoodEntriesClient,
  MyFitnessPalSettingsClient,
  ConnectorStatusClient,
  CorrelationClient,
  CountClient,
  DebugClient,
  DeduplicationClient,
  DeviceAgeClient,
  DeviceAlertsClient,
  DeviceHealthClient,
  DeviceStatusClient,
  DiscrepancyClient,
  EntriesClient,
  FoodClient,
  FoodsClient,
  GlucoseClient,
  HeartRateClient,
  InsulinClient,
  IobClient,
  LastModifiedClient,
  LocalAuthClient,
  LoopClient,
  MealMatchingClient,
  MetadataClient,
  MigrationClient,
  NotificationsClient,
  NutritionClient,
  ObservationsClient,
  OidcClient,
  WellKnownClient,
  PebbleClient,
  PredictionClient,
  ProcessingClient,
  ProfileClient,
  RetrospectiveClient,
  ServicesClient,
  SettingsClient,
  StateSpansClient,
  StatisticsClient,
  StatusClient,
  StepCountClient,
  SystemEventsClient,
  TimeQueryClient,
  TrackerAlertsClient,
  TrackersClient,
  TreatmentsClient,
  UISettingsClient,
  UserPreferencesClient,
  DDataClient,
  PropertiesClient,
  SummaryClient,
  VersionClient,
  VersionsClient,
  WebhookSettingsClient
} from "./generated/nocturne-api-client";

/**
 * API client wrapper for the Nocturne API.
 * Provides typed access to all backend endpoints.
 */
export class ApiClient {
  public readonly baseUrl: string;
  public readonly activity: ActivityClient;
  public readonly admin: BackfillClient;
  public readonly alexa: AlexaClient;
  public readonly analytics: AnalyticsClient;
  public readonly authentication: AuthenticationClient;
  public readonly authorization: AuthorizationClient;
  public readonly battery: BatteryClient;
  public readonly chartData: ChartDataClient;
  public readonly clockFaces: ClockFacesClient;
  public readonly compatibility: CompatibilityClient;
  public readonly compressionLows: CompressionLowClient;
  public readonly configuration: ConfigurationClient;
  public readonly connectorFoodEntries: ConnectorFoodEntriesClient;
  public readonly connectorSettings: MyFitnessPalSettingsClient;
  public readonly connectorStatus: ConnectorStatusClient;
  public readonly correlation: CorrelationClient;
  public readonly count: CountClient;
  public readonly debug: DebugClient;
  public readonly deduplication: DeduplicationClient;
  public readonly deviceAge: DeviceAgeClient;
  public readonly deviceAlerts: DeviceAlertsClient;
  public readonly deviceHealth: DeviceHealthClient;
  public readonly deviceStatus: DeviceStatusClient;
  public readonly discrepancy: DiscrepancyClient;
  public readonly entries: EntriesClient;
  public readonly food: FoodClient;
  public readonly foodsV4: FoodsClient;
  public readonly glucose: GlucoseClient;
  public readonly heartRate: HeartRateClient;
  public readonly insulin: InsulinClient;
  public readonly iob: IobClient;
  public readonly lastModified: LastModifiedClient;
  public readonly localAuth: LocalAuthClient;
  public readonly loopNotifications: LoopClient;
  public readonly mealMatching: MealMatchingClient;
  public readonly metadata: MetadataClient;
  public readonly migration: MigrationClient;
  public readonly notifications: NotificationsClient;
  public readonly nutrition: NutritionClient;
  public readonly observations: ObservationsClient;
  public readonly oidc: OidcClient;
  public readonly oidcDiscovery: WellKnownClient;
  public readonly pebble: PebbleClient;
  public readonly predictions: PredictionClient;
  public readonly processing: ProcessingClient;
  public readonly profile: ProfileClient;
  public readonly retrospective: RetrospectiveClient;
  public readonly services: ServicesClient;
  public readonly settings: SettingsClient;
  public readonly stateSpans: StateSpansClient;
  public readonly statistics: StatisticsClient;
  public readonly status: StatusClient;
  public readonly stepCount: StepCountClient;
  public readonly systemEvents: SystemEventsClient;
  public readonly timeQuery: TimeQueryClient;
  public readonly trackerAlerts: TrackerAlertsClient;
  public readonly trackers: TrackersClient;
  public readonly treatments: TreatmentsClient;
  public readonly uiSettings: UISettingsClient;
  public readonly userPreferences: UserPreferencesClient;
  public readonly v2DData: DDataClient;
  public readonly v2Properties: PropertiesClient;
  public readonly v2Summary: SummaryClient;
  public readonly version: VersionClient;
  public readonly versions: VersionsClient;
  public readonly webhookSettings: WebhookSettingsClient;

  constructor(
    baseUrl: string,
    http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }
  ) {
    const apiBaseUrl = baseUrl;
    this.baseUrl = apiBaseUrl;

    this.activity = new ActivityClient(apiBaseUrl, http);
    this.admin = new BackfillClient(apiBaseUrl, http);
    this.alexa = new AlexaClient(apiBaseUrl, http);
    this.analytics = new AnalyticsClient(apiBaseUrl, http);
    this.authentication = new AuthenticationClient(apiBaseUrl, http);
    this.authorization = new AuthorizationClient(apiBaseUrl, http);
    this.battery = new BatteryClient(apiBaseUrl, http);
    this.chartData = new ChartDataClient(apiBaseUrl, http);
    this.clockFaces = new ClockFacesClient(apiBaseUrl, http);
    this.compatibility = new CompatibilityClient(apiBaseUrl, http);
    this.compressionLows = new CompressionLowClient(apiBaseUrl, http);
    this.configuration = new ConfigurationClient(apiBaseUrl, http);
    this.connectorFoodEntries = new ConnectorFoodEntriesClient(apiBaseUrl, http);
    this.connectorSettings = new MyFitnessPalSettingsClient(apiBaseUrl, http);
    this.connectorStatus = new ConnectorStatusClient(apiBaseUrl, http);
    this.correlation = new CorrelationClient(apiBaseUrl, http);
    this.count = new CountClient(apiBaseUrl, http);
    this.debug = new DebugClient(apiBaseUrl, http);
    this.deduplication = new DeduplicationClient(apiBaseUrl, http);
    this.deviceAge = new DeviceAgeClient(apiBaseUrl, http);
    this.deviceAlerts = new DeviceAlertsClient(apiBaseUrl, http);
    this.deviceHealth = new DeviceHealthClient(apiBaseUrl, http);
    this.deviceStatus = new DeviceStatusClient(apiBaseUrl, http);
    this.discrepancy = new DiscrepancyClient(apiBaseUrl, http);
    this.entries = new EntriesClient(apiBaseUrl, http);
    this.food = new FoodClient(apiBaseUrl, http);
    this.foodsV4 = new FoodsClient(apiBaseUrl, http);
    this.glucose = new GlucoseClient(apiBaseUrl, http);
    this.heartRate = new HeartRateClient(apiBaseUrl, http);
    this.insulin = new InsulinClient(apiBaseUrl, http);
    this.iob = new IobClient(apiBaseUrl, http);
    this.lastModified = new LastModifiedClient(apiBaseUrl, http);
    this.localAuth = new LocalAuthClient(apiBaseUrl, http);
    this.loopNotifications = new LoopClient(apiBaseUrl, http);
    this.mealMatching = new MealMatchingClient(apiBaseUrl, http);
    this.metadata = new MetadataClient(apiBaseUrl, http);
    this.migration = new MigrationClient(apiBaseUrl, http);
    this.notifications = new NotificationsClient(apiBaseUrl, http);
    this.nutrition = new NutritionClient(apiBaseUrl, http);
    this.observations = new ObservationsClient(apiBaseUrl, http);
    this.oidc = new OidcClient(apiBaseUrl, http);
    this.oidcDiscovery = new WellKnownClient(apiBaseUrl, http);
    this.pebble = new PebbleClient(apiBaseUrl, http);
    this.predictions = new PredictionClient(apiBaseUrl, http);
    this.processing = new ProcessingClient(apiBaseUrl, http);
    this.profile = new ProfileClient(apiBaseUrl, http);
    this.retrospective = new RetrospectiveClient(apiBaseUrl, http);
    this.services = new ServicesClient(apiBaseUrl, http);
    this.settings = new SettingsClient(apiBaseUrl, http);
    this.stateSpans = new StateSpansClient(apiBaseUrl, http);
    this.statistics = new StatisticsClient(apiBaseUrl, http);
    this.status = new StatusClient(apiBaseUrl, http);
    this.stepCount = new StepCountClient(apiBaseUrl, http);
    this.systemEvents = new SystemEventsClient(apiBaseUrl, http);
    this.timeQuery = new TimeQueryClient(apiBaseUrl, http);
    this.trackerAlerts = new TrackerAlertsClient(apiBaseUrl, http);
    this.trackers = new TrackersClient(apiBaseUrl, http);
    this.treatments = new TreatmentsClient(apiBaseUrl, http);
    this.uiSettings = new UISettingsClient(apiBaseUrl, http);
    this.userPreferences = new UserPreferencesClient(apiBaseUrl, http);
    this.v2DData = new DDataClient(apiBaseUrl, http);
    this.v2Properties = new PropertiesClient(apiBaseUrl, http);
    this.v2Summary = new SummaryClient(apiBaseUrl, http);
    this.version = new VersionClient(apiBaseUrl, http);
    this.versions = new VersionsClient(apiBaseUrl, http);
    this.webhookSettings = new WebhookSettingsClient(apiBaseUrl, http);
  }
}

// Export the generated client types for use in components
export * from "./generated/nocturne-api-client";
