// AUTO-GENERATED - DO NOT EDIT
// Generated by @nocturne/remote-function-codegen
// Source: openapi.json
//
// Note: Property names are derived from the shared tag-to-property mapping.
// Some may need manual adjustment to match existing api-client.ts conventions.

import {
  ActivityClient,
  AlexaClient,
  AnalyticsClient,
  AuthenticationClient,
  AuthorizationClient,
  BatteryClient,
  Chart DataClient,
  Clock FacesClient,
  CompatibilityClient,
  ConfigurationClient,
  Connector Food EntriesClient,
  Connector SettingsClient,
  ConnectorStatusClient,
  CountClient,
  DebugClient,
  DebugClient,
  DeduplicationClient,
  Device AgeClient,
  Device AlertsClient,
  Device HealthClient,
  DeviceStatusClient,
  DiscrepancyClient,
  EntriesClient,
  FoodClient,
  FoodsClient,
  IOBClient,
  LastModifiedClient,
  Loop NotificationsClient,
  Meal MatchingClient,
  MetadataClient,
  MigrationClient,
  OIDC DiscoveryClient,
  PebbleClient,
  PredictionClient,
  ProcessingClient,
  ProfileClient,
  RetrospectiveClient,
  ServicesClient,
  SettingsClient,
  StateSpansClient,
  StatisticsClient,
  StatusClient,
  SystemEventsClient,
  TimeQueryClient,
  Tracker AlertsClient,
  TrackersClient,
  Treatment FoodsClient,
  TreatmentsClient,
  TreatmentsClient,
  UISettingsClient,
  User PreferencesClient,
  DDataClient,
  NotificationsClient,
  NotificationsClient,
  NotificationsClient,
  PropertiesClient,
  SummaryClient,
  VersionClient,
  VersionsClient,
  WebhookSettingsClient
} from "./generated/nocturne-api-client";

/**
 * API client wrapper for the Nocturne API.
 * Provides typed access to all backend endpoints.
 */
export class ApiClient {
  public readonly baseUrl: string;
  public readonly activity: ActivityClient;
  public readonly alexa: AlexaClient;
  public readonly analytics: AnalyticsClient;
  public readonly authentication: AuthenticationClient;
  public readonly authorization: AuthorizationClient;
  public readonly battery: BatteryClient;
  public readonly chart Data: Chart DataClient;
  public readonly clock Faces: Clock FacesClient;
  public readonly compatibility: CompatibilityClient;
  public readonly configuration: ConfigurationClient;
  public readonly connector Food Entries: Connector Food EntriesClient;
  public readonly connector Settings: Connector SettingsClient;
  public readonly connectorStatus: ConnectorStatusClient;
  public readonly count: CountClient;
  public readonly debug: DebugClient;
  public readonly debug: DebugClient;
  public readonly deduplication: DeduplicationClient;
  public readonly device Age: Device AgeClient;
  public readonly device Alerts: Device AlertsClient;
  public readonly device Health: Device HealthClient;
  public readonly deviceStatus: DeviceStatusClient;
  public readonly discrepancy: DiscrepancyClient;
  public readonly entries: EntriesClient;
  public readonly food: FoodClient;
  public readonly foodsV4: FoodsClient;
  public readonly iOB: IOBClient;
  public readonly lastModified: LastModifiedClient;
  public readonly loop Notifications: Loop NotificationsClient;
  public readonly meal Matching: Meal MatchingClient;
  public readonly metadata: MetadataClient;
  public readonly migration: MigrationClient;
  public readonly oIDC Discovery: OIDC DiscoveryClient;
  public readonly pebble: PebbleClient;
  public readonly predictions: PredictionClient;
  public readonly processing: ProcessingClient;
  public readonly profile: ProfileClient;
  public readonly retrospective: RetrospectiveClient;
  public readonly services: ServicesClient;
  public readonly settings: SettingsClient;
  public readonly stateSpans: StateSpansClient;
  public readonly statistics: StatisticsClient;
  public readonly status: StatusClient;
  public readonly systemEvents: SystemEventsClient;
  public readonly timeQuery: TimeQueryClient;
  public readonly tracker Alerts: Tracker AlertsClient;
  public readonly trackers: TrackersClient;
  public readonly treatment Foods: Treatment FoodsClient;
  public readonly treatments: TreatmentsClient;
  public readonly treatments: TreatmentsClient;
  public readonly uISettings: UISettingsClient;
  public readonly user Preferences: User PreferencesClient;
  public readonly v2DData: DDataClient;
  public readonly v2Notifications: NotificationsClient;
  public readonly v2Notifications: NotificationsClient;
  public readonly v2Notifications: NotificationsClient;
  public readonly v2Properties: PropertiesClient;
  public readonly v2Summary: SummaryClient;
  public readonly version: VersionClient;
  public readonly versions: VersionsClient;
  public readonly webhookSettings: WebhookSettingsClient;

  constructor(
    baseUrl: string,
    http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }
  ) {
    const apiBaseUrl = baseUrl;
    this.baseUrl = apiBaseUrl;

    this.activity = new ActivityClient(apiBaseUrl, http);
    this.alexa = new AlexaClient(apiBaseUrl, http);
    this.analytics = new AnalyticsClient(apiBaseUrl, http);
    this.authentication = new AuthenticationClient(apiBaseUrl, http);
    this.authorization = new AuthorizationClient(apiBaseUrl, http);
    this.battery = new BatteryClient(apiBaseUrl, http);
    this.chart Data = new Chart DataClient(apiBaseUrl, http);
    this.clock Faces = new Clock FacesClient(apiBaseUrl, http);
    this.compatibility = new CompatibilityClient(apiBaseUrl, http);
    this.configuration = new ConfigurationClient(apiBaseUrl, http);
    this.connector Food Entries = new Connector Food EntriesClient(apiBaseUrl, http);
    this.connector Settings = new Connector SettingsClient(apiBaseUrl, http);
    this.connectorStatus = new ConnectorStatusClient(apiBaseUrl, http);
    this.count = new CountClient(apiBaseUrl, http);
    this.debug = new DebugClient(apiBaseUrl, http);
    this.debug = new DebugClient(apiBaseUrl, http);
    this.deduplication = new DeduplicationClient(apiBaseUrl, http);
    this.device Age = new Device AgeClient(apiBaseUrl, http);
    this.device Alerts = new Device AlertsClient(apiBaseUrl, http);
    this.device Health = new Device HealthClient(apiBaseUrl, http);
    this.deviceStatus = new DeviceStatusClient(apiBaseUrl, http);
    this.discrepancy = new DiscrepancyClient(apiBaseUrl, http);
    this.entries = new EntriesClient(apiBaseUrl, http);
    this.food = new FoodClient(apiBaseUrl, http);
    this.foodsV4 = new FoodsClient(apiBaseUrl, http);
    this.iOB = new IOBClient(apiBaseUrl, http);
    this.lastModified = new LastModifiedClient(apiBaseUrl, http);
    this.loop Notifications = new Loop NotificationsClient(apiBaseUrl, http);
    this.meal Matching = new Meal MatchingClient(apiBaseUrl, http);
    this.metadata = new MetadataClient(apiBaseUrl, http);
    this.migration = new MigrationClient(apiBaseUrl, http);
    this.oIDC Discovery = new OIDC DiscoveryClient(apiBaseUrl, http);
    this.pebble = new PebbleClient(apiBaseUrl, http);
    this.predictions = new PredictionClient(apiBaseUrl, http);
    this.processing = new ProcessingClient(apiBaseUrl, http);
    this.profile = new ProfileClient(apiBaseUrl, http);
    this.retrospective = new RetrospectiveClient(apiBaseUrl, http);
    this.services = new ServicesClient(apiBaseUrl, http);
    this.settings = new SettingsClient(apiBaseUrl, http);
    this.stateSpans = new StateSpansClient(apiBaseUrl, http);
    this.statistics = new StatisticsClient(apiBaseUrl, http);
    this.status = new StatusClient(apiBaseUrl, http);
    this.systemEvents = new SystemEventsClient(apiBaseUrl, http);
    this.timeQuery = new TimeQueryClient(apiBaseUrl, http);
    this.tracker Alerts = new Tracker AlertsClient(apiBaseUrl, http);
    this.trackers = new TrackersClient(apiBaseUrl, http);
    this.treatment Foods = new Treatment FoodsClient(apiBaseUrl, http);
    this.treatments = new TreatmentsClient(apiBaseUrl, http);
    this.treatments = new TreatmentsClient(apiBaseUrl, http);
    this.uISettings = new UISettingsClient(apiBaseUrl, http);
    this.user Preferences = new User PreferencesClient(apiBaseUrl, http);
    this.v2DData = new DDataClient(apiBaseUrl, http);
    this.v2Notifications = new NotificationsClient(apiBaseUrl, http);
    this.v2Notifications = new NotificationsClient(apiBaseUrl, http);
    this.v2Notifications = new NotificationsClient(apiBaseUrl, http);
    this.v2Properties = new PropertiesClient(apiBaseUrl, http);
    this.v2Summary = new SummaryClient(apiBaseUrl, http);
    this.version = new VersionClient(apiBaseUrl, http);
    this.versions = new VersionsClient(apiBaseUrl, http);
    this.webhookSettings = new WebhookSettingsClient(apiBaseUrl, http);
  }
}

// Export the generated client types for use in components
export * from "./generated/nocturne-api-client";
