// src/Web/packages/remote-function-codegen/src/generators/api-client.ts
import type { OpenAPIV3 } from 'openapi-types';
import { getClientPropertyName } from '../utils/client-mapping.js';

interface ClientInfo {
  className: string;
  propertyName: string;
}

/**
 * Generate the ApiClient wrapper class.
 *
 * Note: This produces a reference version. The existing api-client.ts
 * has custom property names and should be maintained manually.
 */
export function generateApiClient(spec: OpenAPIV3.Document): string {
  // Extract all unique tags (which map to NSwag client classes)
  const tags = new Set<string>();

  for (const pathItem of Object.values(spec.paths ?? {})) {
    if (!pathItem) continue;

    for (const method of ['get', 'post', 'put', 'patch', 'delete'] as const) {
      const operation = pathItem[method] as OpenAPIV3.OperationObject | undefined;
      if (operation?.tags?.[0]) {
        tags.add(operation.tags[0]);
      }
    }
  }

  const clients = Array.from(tags).map(tagToClientInfo).sort((a, b) =>
    a.propertyName.localeCompare(b.propertyName)
  );

  const imports = clients.map(c => c.className).join(',\n  ');
  const properties = clients.map(c => `  public readonly ${c.propertyName}: ${c.className};`).join('\n');
  const initializers = clients.map(c =>
    `    this.${c.propertyName} = new ${c.className}(apiBaseUrl, http);`
  ).join('\n');

  return `// AUTO-GENERATED - DO NOT EDIT
// Generated by @nocturne/remote-function-codegen
// Source: openapi.json
//
// Note: Property names are derived from the shared tag-to-property mapping.
// Some may need manual adjustment to match existing api-client.ts conventions.

import {
  ${imports}
} from "./generated/nocturne-api-client";

/**
 * API client wrapper for the Nocturne API.
 * Provides typed access to all backend endpoints.
 */
export class ApiClient {
  public readonly baseUrl: string;
${properties}

  constructor(
    baseUrl: string,
    http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }
  ) {
    const apiBaseUrl = baseUrl;
    this.baseUrl = apiBaseUrl;

${initializers}
  }
}

// Export the generated client types for use in components
export * from "./generated/nocturne-api-client";
`;
}

/**
 * Convert a tag name to client info (class name and property name).
 * NSwag generates class names like "TrackersClient", "EntriesClient".
 * Property names use the shared tag-to-property mapping.
 */
function tagToClientInfo(tag: string): ClientInfo {
  const cleaned = tag.replace(/^V\d+\s*/i, '');
  return {
    className: `${cleaned}Client`,
    propertyName: getClientPropertyName(tag),
  };
}
