// src/Web/packages/remote-function-codegen/src/generators/api-client.ts
import type { OpenAPIV3 } from 'openapi-types';
import { getClientPropertyName } from '../utils/client-mapping.js';

/**
 * Generate the ApiClient wrapper class.
 *
 * Note: This produces a reference version. The existing api-client.ts
 * has custom property names and should be maintained manually.
 */
export function generateApiClient(spec: OpenAPIV3.Document): string {
  // Map each tag to its NSwag client class name and optional client property override
  type TagInfo = { prefix: string; clientProperty?: string };
  const tagInfo = new Map<string, TagInfo>();

  for (const pathItem of Object.values(spec.paths ?? {})) {
    if (!pathItem) continue;

    for (const method of ['get', 'post', 'put', 'patch', 'delete'] as const) {
      const operation = pathItem[method] as (OpenAPIV3.OperationObject & { 'x-client-property'?: string }) | undefined;
      if (operation?.tags?.[0] && operation.operationId) {
        const tag = operation.tags[0];
        if (!tagInfo.has(tag)) {
          const prefix = operation.operationId.split('_')[0];
          tagInfo.set(tag, {
            prefix,
            clientProperty: operation['x-client-property'],
          });
        }
      }
    }
  }

  // Deduplicate by className (NSwag merges tags like "Treatments" and "V4 Treatments"
  // into a single TreatmentsClient)
  const seen = new Set<string>();
  const clients = Array.from(tagInfo.entries())
    .map(([tag, info]) => ({
      className: `${info.prefix}Client`,
      propertyName: info.clientProperty ?? getClientPropertyName(tag),
    }))
    .filter(c => {
      if (seen.has(c.className)) return false;
      seen.add(c.className);
      return true;
    })
    .sort((a, b) => a.propertyName.localeCompare(b.propertyName));

  const imports = clients.map(c => c.className).join(',\n  ');
  const properties = clients.map(c => `  public readonly ${c.propertyName}: ${c.className};`).join('\n');
  const initializers = clients.map(c =>
    `    this.${c.propertyName} = new ${c.className}(apiBaseUrl, http);`
  ).join('\n');

  return `// AUTO-GENERATED - DO NOT EDIT
// Generated by @nocturne/remote-function-codegen
// Source: openapi.json
//
// Note: Property names are derived from the shared tag-to-property mapping.
// Some may need manual adjustment to match existing api-client.ts conventions.

import {
  ${imports}
} from "./generated/nocturne-api-client";

/**
 * API client wrapper for the Nocturne API.
 * Provides typed access to all backend endpoints.
 */
export class ApiClient {
  public readonly baseUrl: string;
${properties}

  constructor(
    baseUrl: string,
    http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }
  ) {
    const apiBaseUrl = baseUrl;
    this.baseUrl = apiBaseUrl;

${initializers}
  }
}

// Export the generated client types for use in components
export * from "./generated/nocturne-api-client";
`;
}

