// Dashboard Widgets - Individual configurable widget components
export { default as WidgetCard } from "./WidgetCard.svelte";
export { default as CurrentGlucoseWidget } from "./CurrentGlucoseWidget.svelte";
export { default as LastUpdatedWidget } from "./LastUpdatedWidget.svelte";
export { default as ConnectionStatusWidget } from "./ConnectionStatusWidget.svelte";
export { default as MealsWidget } from "./MealsWidget.svelte";
export { default as TrackersWidget } from "./TrackersWidget.svelte";
export { default as TirChartWidget } from "./TirChartWidget.svelte";
export { default as DailySummaryWidget } from "./DailySummaryWidget.svelte";
